---
name: "Nautobot Upstream Monitor"

on:  # yamllint disable-line rule:truthy rule:comments
  workflow_dispatch:

jobs:
  upstream-test:
    uses: "nautobot/nautobot/.github/workflows/plugin_upstream_testing_base.yml@u/gas-fix-upstream-testing-status"
    with:  # Below could potentially be collapsed into a single argument if a concrete relationship between both is enforced
      invoke_context_name: "NAUTOBOT_SSOT"
      plugin_name: "nautobot-app-ssot"
